# Generated by Django 5.2 on 2025-04-25 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin_name', models.CharField(max_length=255)),
                ('german_name', models.CharField(max_length=255)),
                ('english_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TreeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('credit_user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_url', models.URLField(blank=True, null=True)),
                ('tree_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees_of_germany.treespecies')),
            ],
        ),
    ]
