# Generated by Django 5.2 on 2025-05-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('german_with_videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordLearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('original_word_string', models.CharField(max_length=100)),
                ('selected_button', models.CharField(max_length=100)),
                ('snippet_identifier', models.CharField(max_length=100)),
            ],
        ),
    ]
