# Generated by Django 5.2 on 2025-05-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangles', '0003_distractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_congruence_theorem',
            field=models.BooleanField(default=False),
        ),
    ]
