# Generated by Django 5.2 on 2025-05-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangles', '0004_topic_is_congruence_theorem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningevent',
            name='image_exercise_template',
        ),
        migrations.AddField(
            model_name='learningevent',
            name='exercise_type',
            field=models.CharField(default='', help_text='The type of exercise that was completed', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_congruence_theorem',
            field=models.BooleanField(default=False, help_text='If True, this topic represents a triangle congruence theorem (SSS, SSW, SWS, or WSW)'),
        ),
        migrations.DeleteModel(
            name='ImageExerciseProgress',
        ),
    ]
