# Generated by Django 5.2 on 2025-05-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangles', '0005_remove_learningevent_image_exercise_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprogress',
            name='highest_achieved_streak',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='clozetemplategapprogress',
            name='streak',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='topicprogress',
            name='streak',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
