# Generated by Django 5.2 on 2025-05-19 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MushroomSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin_name', models.CharField(max_length=255)),
                ('german_name', models.CharField(max_length=255)),
                ('english_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MushroomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('credit_user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_url', models.URLField(blank=True, null=True)),
                ('mushroom_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mushrooms.mushroomspecies')),
            ],
        ),
    ]
