# Generated by Django 5.2 on 2025-04-26 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('a', models.CharField(max_length=1)),
                ('e', models.CharField(max_length=1)),
                ('c', models.CharField(max_length=1)),
                ('g', models.CharField(max_length=1)),
                ('tab_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uke_fingerpicking.tabsheet')),
            ],
        ),
    ]
