# Generated by Django 5.2 on 2025-04-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withvideos', '0002_language_video_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='frontend',
        ),
    ]
