# Generated by Django 5.2 on 2025-04-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withvideos', '0003_remove_video_frontend'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='subtitle_prefix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
